spring:
  profiles:
    active: dev

---
server:
  port: 8888
# spring的配置dev
spring:
  profiles: dev
  application:
    name: sc-provider-dept
# eureka客户端配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
---
server:
  port: 9999
# spring的配置test
spring:
  profiles: test
  application:
    name: sc-provider-dept
# eureka客户端配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/