spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
server:
  port: 9000

# mybatis配置
mybatis:
  type-aliases-package: com.wang.sc.pojo
  config-locations: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml



# spring配置
spring:
  application:
    name: sc-dept-provider-${server.port}  # 三个提供者的名字一定要一样，因为是通过名字访问的提供者
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 8023love

# eureka客户端配置
eureka:
  client:
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: sc-provider-hystrix-9000
#    prefer-ip-address: false  #显示为true可显示ip地址

# info 配置
info:
  app.name: wangd1'sc
  company.name: wangd1'company

---
spring:
  profiles: test
server:
  port: 9000

# mybatis配置
mybatis:
  type-aliases-package: com.wang.sc.pojo
  config-locations: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml



# spring配置
spring:
  application:
    name: sc-dept-provider-${server.port}  # 三个提供者的名字一定要一样，因为是通过名字访问的提供者
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 8023love

# eureka客户端配置
eureka:
  client:
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: sc-provider-hystrix-9000
#    prefer-ip-address: false  #显示为true可显示ip地址

# info 配置
info:
  app.name: wangd1'sc
  company.name: wangd1'company
