spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: sc-config-consumer-${server.port}
server:
  port: 8001

eureka:
  client:
    register-with-eureka: false #不向eureka注册自己，因为是消费者
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

# feign.hystrix服务降级开启
feign:
  hystrix:
    enabled: true

---
---
spring:
  profiles: test
  application:
    name: sc-config-consumer-${server.port}
server:
  port: 8011

eureka:
  client:
    register-with-eureka: false #不向eureka注册自己，因为是消费者
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

# feign.hystrix服务降级开启
feign:
  hystrix:
    enabled: true
